name: unsure
description: An easy uncertainty calculator.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.3
  petitparser: ^3.0.1
  t_stats: ^2.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
